# Generated by Django 3.2.6 on 2021-08-28 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('uid', models.CharField(max_length=10, verbose_name='学号')),
                ('name', models.CharField(max_length=6, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=20, verbose_name='邮箱')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='JoinedTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student', verbose_name='所属学生')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tutorial', verbose_name='所属老师')),
            ],
            options={
                'verbose_name': '学生已参加的辅导',
                'verbose_name_plural': '学生已参加的辅导',
                'db_table': 'JoinedTutorial',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='JoinedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.course', verbose_name='参加的课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student', verbose_name='所属学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher', verbose_name='所属老师')),
            ],
            options={
                'verbose_name': '学生已参加的课程',
                'verbose_name_plural': '学生已参加的课程',
                'db_table': 'joined_course',
                'get_latest_by': 'id',
            },
        ),
    ]
