# Generated by Django 3.2.6 on 2021-08-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20210829_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
