# Generated by Django 3.2.6 on 2021-08-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_remove_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.CharField(max_length=10, unique=True, verbose_name='学号'),
        ),
    ]
