# Generated by Django 3.2.6 on 2021-09-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_alter_joinedtutorial_tutorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'get_latest_by': 'id', 'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AddField(
            model_name='joinedtutorial',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.jpg', upload_to='avatar', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='student',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='微信openid'),
        ),
    ]
