# Generated by Django 3.2.6 on 2021-08-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=6, verbose_name='姓名'),
        ),
    ]
