# Generated by Django 3.2.6 on 2021-08-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_remove_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='uid',
            field=models.CharField(max_length=10, unique=True, verbose_name='工号'),
        ),
    ]
