# Generated by Django 3.2.6 on 2021-09-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0007_alter_course_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='wallpaper',
            field=models.URLField(blank=True, default='http://www.louisyoung.site:8002/TutorialManage/wallpaper.jpg', verbose_name='背景'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.URLField(blank=True, default='http://www.louisyoung.site:8002/TutorialManage/avatar.jpg', null=True, verbose_name='头像'),
        ),
    ]
