# Generated by Django 3.2.6 on 2021-09-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0008_auto_20210905_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=10, verbose_name='课程'),
        ),
    ]
