# Generated by Django 3.2.6 on 2021-09-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0009_alter_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='end_time',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='duration_time',
            field=models.FloatField(default=2.0, verbose_name='持续时间'),
        ),
    ]
